<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Absen_detailsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('absen_details')->insert([
            ['absen_detail_id' => 1, 'absensi_id' => 1, 'anggota_id' => 1, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 2, 'absensi_id' => 2, 'anggota_id' => 6, 'absen_status' => 'Sakit', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 3, 'absensi_id' => 2, 'anggota_id' => 4, 'absen_status' => 'Dinas', 'absen_note' => 'Luar Kota'],
            ['absen_detail_id' => 4, 'absensi_id' => 3, 'anggota_id' => 1, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 5, 'absensi_id' => 3, 'anggota_id' => 2, 'absen_status' => 'Izin', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 6, 'absensi_id' => 3, 'anggota_id' => 3, 'absen_status' => 'Izin', 'absen_note' => 'Batuk'],
            ['absen_detail_id' => 7, 'absensi_id' => 4, 'anggota_id' => 6, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 8, 'absensi_id' => 4, 'anggota_id' => 4, 'absen_status' => 'Sakit', 'absen_note' => 'Panas'],
            ['absen_detail_id' => 9, 'absensi_id' => 5, 'anggota_id' => 9, 'absen_status' => 'Izin', 'absen_note' => 'Urusan Keluarga'],
            ['absen_detail_id' => 10, 'absensi_id' => 6, 'anggota_id' => 14, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 11, 'absensi_id' => 6, 'anggota_id' => 12, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 12, 'absensi_id' => 7, 'anggota_id' => 9, 'absen_status' => 'Dinas', 'absen_note' => 'Kalimantan'],
            ['absen_detail_id' => 13, 'absensi_id' => 7, 'anggota_id' => 10, 'absen_status' => 'Sakit', 'absen_note' => 'Diare'],
            ['absen_detail_id' => 14, 'absensi_id' => 7, 'anggota_id' => 11, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 15, 'absensi_id' => 8, 'anggota_id' => 14, 'absen_status' => 'Sakit', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 16, 'absensi_id' => 8, 'anggota_id' => 12, 'absen_status' => 'Dinas', 'absen_note' => 'Luar Kota'],
            ['absen_detail_id' => 17, 'absensi_id' => 9, 'anggota_id' => 17, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 18, 'absensi_id' => 10, 'anggota_id' => 22, 'absen_status' => 'Izin', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 19, 'absensi_id' => 10, 'anggota_id' => 20, 'absen_status' => 'Izin', 'absen_note' => 'Batuk'],
            ['absen_detail_id' => 20, 'absensi_id' => 11, 'anggota_id' => 17, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 21, 'absensi_id' => 11, 'anggota_id' => 18, 'absen_status' => 'Sakit', 'absen_note' => 'Panas'],
            ['absen_detail_id' => 22, 'absensi_id' => 11, 'anggota_id' => 19, 'absen_status' => 'Izin', 'absen_note' => 'Urusan Keluarga'],
            ['absen_detail_id' => 23, 'absensi_id' => 12, 'anggota_id' => 22, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 24, 'absensi_id' => 12, 'anggota_id' => 20, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 25, 'absensi_id' => 13, 'anggota_id' => 25, 'absen_status' => 'Dinas', 'absen_note' => 'Kalimantan'],
            ['absen_detail_id' => 26, 'absensi_id' => 14, 'anggota_id' => 30, 'absen_status' => 'Sakit', 'absen_note' => 'Diare'],
            ['absen_detail_id' => 27, 'absensi_id' => 14, 'anggota_id' => 28, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 28, 'absensi_id' => 15, 'anggota_id' => 25, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 29, 'absensi_id' => 15, 'anggota_id' => 26, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 30, 'absensi_id' => 15, 'anggota_id' => 27, 'absen_status' => 'Sakit', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 31, 'absensi_id' => 16, 'anggota_id' => 30, 'absen_status' => 'Dinas', 'absen_note' => 'Luar Kota'],
            ['absen_detail_id' => 32, 'absensi_id' => 16, 'anggota_id' => 28, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 33, 'absensi_id' => 17, 'anggota_id' => 33, 'absen_status' => 'Izin', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 34, 'absensi_id' => 18, 'anggota_id' => 38, 'absen_status' => 'Izin', 'absen_note' => 'Batuk'],
            ['absen_detail_id' => 35, 'absensi_id' => 18, 'anggota_id' => 36, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 36, 'absensi_id' => 19, 'anggota_id' => 33, 'absen_status' => 'Sakit', 'absen_note' => 'Panas'],
            ['absen_detail_id' => 37, 'absensi_id' => 19, 'anggota_id' => 34, 'absen_status' => 'Izin', 'absen_note' => 'Urusan Keluarga'],
            ['absen_detail_id' => 38, 'absensi_id' => 19, 'anggota_id' => 35, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 39, 'absensi_id' => 20, 'anggota_id' => 38, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 40, 'absensi_id' => 20, 'anggota_id' => 36, 'absen_status' => 'Dinas', 'absen_note' => 'Kalimantan'],
            ['absen_detail_id' => 41, 'absensi_id' => 21, 'anggota_id' => 41, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 42, 'absensi_id' => 22, 'anggota_id' => 46, 'absen_status' => 'Sakit', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 43, 'absensi_id' => 22, 'anggota_id' => 44, 'absen_status' => 'Dinas', 'absen_note' => 'Luar Kota'],
            ['absen_detail_id' => 44, 'absensi_id' => 23, 'anggota_id' => 41, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 45, 'absensi_id' => 23, 'anggota_id' => 42, 'absen_status' => 'Izin', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 46, 'absensi_id' => 23, 'anggota_id' => 43, 'absen_status' => 'Izin', 'absen_note' => 'Batuk'],
            ['absen_detail_id' => 47, 'absensi_id' => 24, 'anggota_id' => 46, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 48, 'absensi_id' => 24, 'anggota_id' => 44, 'absen_status' => 'Sakit', 'absen_note' => 'Panas'],
            ['absen_detail_id' => 49, 'absensi_id' => 25, 'anggota_id' => 49, 'absen_status' => 'Izin', 'absen_note' => 'Urusan Keluarga'],
            ['absen_detail_id' => 50, 'absensi_id' => 26, 'anggota_id' => 54, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 51, 'absensi_id' => 26, 'anggota_id' => 52, 'absen_status' => 'Sakit', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 52, 'absensi_id' => 27, 'anggota_id' => 49, 'absen_status' => 'Dinas', 'absen_note' => 'Luar Kota'],
            ['absen_detail_id' => 53, 'absensi_id' => 27, 'anggota_id' => 50, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 54, 'absensi_id' => 27, 'anggota_id' => 51, 'absen_status' => 'Izin', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 55, 'absensi_id' => 28, 'anggota_id' => 54, 'absen_status' => 'Izin', 'absen_note' => 'Batuk'],
            ['absen_detail_id' => 56, 'absensi_id' => 28, 'anggota_id' => 52, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 57, 'absensi_id' => 29, 'anggota_id' => 57, 'absen_status' => 'Sakit', 'absen_note' => 'Panas'],
            ['absen_detail_id' => 58, 'absensi_id' => 30, 'anggota_id' => 62, 'absen_status' => 'Izin', 'absen_note' => 'Urusan Keluarga'],
            ['absen_detail_id' => 59, 'absensi_id' => 30, 'anggota_id' => 60, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 60, 'absensi_id' => 31, 'anggota_id' => 57, 'absen_status' => 'Sakit', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 61, 'absensi_id' => 31, 'anggota_id' => 58, 'absen_status' => 'Dinas', 'absen_note' => 'Luar Kota'],
            ['absen_detail_id' => 62, 'absensi_id' => 31, 'anggota_id' => 59, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 63, 'absensi_id' => 32, 'anggota_id' => 62, 'absen_status' => 'Izin', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 64, 'absensi_id' => 32, 'anggota_id' => 60, 'absen_status' => 'Izin', 'absen_note' => 'Batuk'],
            ['absen_detail_id' => 65, 'absensi_id' => 33, 'anggota_id' => 65, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 66, 'absensi_id' => 34, 'anggota_id' => 70, 'absen_status' => 'Sakit', 'absen_note' => 'Panas'],
            ['absen_detail_id' => 67, 'absensi_id' => 34, 'anggota_id' => 68, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 68, 'absensi_id' => 35, 'anggota_id' => 65, 'absen_status' => 'Sakit', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 69, 'absensi_id' => 35, 'anggota_id' => 66, 'absen_status' => 'Dinas', 'absen_note' => 'Luar Kota'],
            ['absen_detail_id' => 70, 'absensi_id' => 35, 'anggota_id' => 67, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 71, 'absensi_id' => 36, 'anggota_id' => 70, 'absen_status' => 'Izin', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 72, 'absensi_id' => 36, 'anggota_id' => 68, 'absen_status' => 'Izin', 'absen_note' => 'Batuk'],
            ['absen_detail_id' => 73, 'absensi_id' => 37, 'anggota_id' => 73, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 74, 'absensi_id' => 38, 'anggota_id' => 78, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 75, 'absensi_id' => 38, 'anggota_id' => 76, 'absen_status' => 'Sakit', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 76, 'absensi_id' => 39, 'anggota_id' => 73, 'absen_status' => 'Dinas', 'absen_note' => 'Luar Kota'],
            ['absen_detail_id' => 77, 'absensi_id' => 39, 'anggota_id' => 74, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 78, 'absensi_id' => 39, 'anggota_id' => 75, 'absen_status' => 'Izin', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 79, 'absensi_id' => 40, 'anggota_id' => 78, 'absen_status' => 'Izin', 'absen_note' => 'Batuk'],
            ['absen_detail_id' => 80, 'absensi_id' => 40, 'anggota_id' => 76, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 81, 'absensi_id' => 41, 'anggota_id' => 81, 'absen_status' => 'Sakit', 'absen_note' => 'Panas'],
            ['absen_detail_id' => 82, 'absensi_id' => 42, 'anggota_id' => 86, 'absen_status' => 'Izin', 'absen_note' => 'Urusan Keluarga'],
            ['absen_detail_id' => 83, 'absensi_id' => 42, 'anggota_id' => 84, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 84, 'absensi_id' => 43, 'anggota_id' => 81, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 85, 'absensi_id' => 43, 'anggota_id' => 82, 'absen_status' => 'Dinas', 'absen_note' => 'Kalimantan'],
            ['absen_detail_id' => 86, 'absensi_id' => 43, 'anggota_id' => 83, 'absen_status' => 'Sakit', 'absen_note' => 'Diare'],
            ['absen_detail_id' => 87, 'absensi_id' => 44, 'anggota_id' => 86, 'absen_status' => 'Izin', 'absen_note' => 'Batuk'],
            ['absen_detail_id' => 88, 'absensi_id' => 44, 'anggota_id' => 84, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 89, 'absensi_id' => 45, 'anggota_id' => 89, 'absen_status' => 'Sakit', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 90, 'absensi_id' => 46, 'anggota_id' => 94, 'absen_status' => 'Dinas', 'absen_note' => 'Luar Kota'],
            ['absen_detail_id' => 91, 'absensi_id' => 46, 'anggota_id' => 92, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 92, 'absensi_id' => 47, 'anggota_id' => 89, 'absen_status' => 'Izin', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 93, 'absensi_id' => 47, 'anggota_id' => 90, 'absen_status' => 'Izin', 'absen_note' => 'Batuk'],
            ['absen_detail_id' => 94, 'absensi_id' => 47, 'anggota_id' => 91, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 95, 'absensi_id' => 48, 'anggota_id' => 94, 'absen_status' => 'Sakit', 'absen_note' => 'Panas'],
            ['absen_detail_id' => 96, 'absensi_id' => 48, 'anggota_id' => 92, 'absen_status' => 'Izin', 'absen_note' => 'Urusan Keluarga'],
            ['absen_detail_id' => 97, 'absensi_id' => 49, 'anggota_id' => 96, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 98, 'absensi_id' => 50, 'anggota_id' => 101, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 99, 'absensi_id' => 50, 'anggota_id' => 99, 'absen_status' => 'Dinas', 'absen_note' => 'Kalimantan'],
            ['absen_detail_id' => 100, 'absensi_id' => 51, 'anggota_id' => 96, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 101, 'absensi_id' => 51, 'anggota_id' => 97, 'absen_status' => 'Sakit', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 102, 'absensi_id' => 51, 'anggota_id' => 98, 'absen_status' => 'Dinas', 'absen_note' => 'Luar Kota'],
            ['absen_detail_id' => 103, 'absensi_id' => 52, 'anggota_id' => 101, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 104, 'absensi_id' => 52, 'anggota_id' => 99, 'absen_status' => 'Izin', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 105, 'absensi_id' => 53, 'anggota_id' => 103, 'absen_status' => 'Izin', 'absen_note' => 'Batuk'],
            ['absen_detail_id' => 106, 'absensi_id' => 54, 'anggota_id' => 108, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 107, 'absensi_id' => 54, 'anggota_id' => 106, 'absen_status' => 'Sakit', 'absen_note' => 'Panas'],
            ['absen_detail_id' => 108, 'absensi_id' => 55, 'anggota_id' => 103, 'absen_status' => 'Izin', 'absen_note' => 'Urusan Keluarga'],
            ['absen_detail_id' => 109, 'absensi_id' => 55, 'anggota_id' => 104, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 110, 'absensi_id' => 55, 'anggota_id' => 105, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 111, 'absensi_id' => 56, 'anggota_id' => 108, 'absen_status' => 'Dinas', 'absen_note' => 'Kalimantan'],
            ['absen_detail_id' => 112, 'absensi_id' => 56, 'anggota_id' => 106, 'absen_status' => 'Sakit', 'absen_note' => 'Diare'],
            ['absen_detail_id' => 113, 'absensi_id' => 57, 'anggota_id' => 110, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 114, 'absensi_id' => 58, 'anggota_id' => 115, 'absen_status' => 'Sakit', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 115, 'absensi_id' => 58, 'anggota_id' => 113, 'absen_status' => 'Dinas', 'absen_note' => 'Luar Kota'],
            ['absen_detail_id' => 116, 'absensi_id' => 59, 'anggota_id' => 110, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 117, 'absensi_id' => 59, 'anggota_id' => 111, 'absen_status' => 'Izin', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 118, 'absensi_id' => 59, 'anggota_id' => 112, 'absen_status' => 'Izin', 'absen_note' => 'Batuk'],
            ['absen_detail_id' => 119, 'absensi_id' => 60, 'anggota_id' => 115, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 120, 'absensi_id' => 60, 'anggota_id' => 113, 'absen_status' => 'Sakit', 'absen_note' => 'Panas'],
            ['absen_detail_id' => 121, 'absensi_id' => 61, 'anggota_id' => 117, 'absen_status' => 'Izin', 'absen_note' => 'Urusan Keluarga'],
            ['absen_detail_id' => 122, 'absensi_id' => 62, 'anggota_id' => 122, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 123, 'absensi_id' => 62, 'anggota_id' => 120, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 124, 'absensi_id' => 63, 'anggota_id' => 117, 'absen_status' => 'Dinas', 'absen_note' => 'Kalimantan'],
            ['absen_detail_id' => 125, 'absensi_id' => 63, 'anggota_id' => 118, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 126, 'absensi_id' => 63, 'anggota_id' => 119, 'absen_status' => 'Sakit', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 127, 'absensi_id' => 64, 'anggota_id' => 122, 'absen_status' => 'Dinas', 'absen_note' => 'Luar Kota'],
            ['absen_detail_id' => 128, 'absensi_id' => 64, 'anggota_id' => 120, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 129, 'absensi_id' => 65, 'anggota_id' => 124, 'absen_status' => 'Izin', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 130, 'absensi_id' => 66, 'anggota_id' => 129, 'absen_status' => 'Izin', 'absen_note' => 'Batuk'],
            ['absen_detail_id' => 131, 'absensi_id' => 66, 'anggota_id' => 127, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 132, 'absensi_id' => 67, 'anggota_id' => 124, 'absen_status' => 'Sakit', 'absen_note' => 'Panas'],
            ['absen_detail_id' => 133, 'absensi_id' => 67, 'anggota_id' => 125, 'absen_status' => 'Izin', 'absen_note' => 'Urusan Keluarga'],
            ['absen_detail_id' => 134, 'absensi_id' => 67, 'anggota_id' => 126, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 135, 'absensi_id' => 68, 'anggota_id' => 129, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 136, 'absensi_id' => 68, 'anggota_id' => 127, 'absen_status' => 'Dinas', 'absen_note' => 'Kalimantan'],
            ['absen_detail_id' => 137, 'absensi_id' => 69, 'anggota_id' => 131, 'absen_status' => 'Sakit', 'absen_note' => 'Diare'],
            ['absen_detail_id' => 138, 'absensi_id' => 70, 'anggota_id' => 136, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 139, 'absensi_id' => 70, 'anggota_id' => 134, 'absen_status' => 'Sakit', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 140, 'absensi_id' => 71, 'anggota_id' => 131, 'absen_status' => 'Dinas', 'absen_note' => 'Luar Kota'],
            ['absen_detail_id' => 141, 'absensi_id' => 71, 'anggota_id' => 132, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 142, 'absensi_id' => 71, 'anggota_id' => 133, 'absen_status' => 'Izin', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 143, 'absensi_id' => 72, 'anggota_id' => 136, 'absen_status' => 'Izin', 'absen_note' => 'Batuk'],
            ['absen_detail_id' => 144, 'absensi_id' => 72, 'anggota_id' => 134, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 145, 'absensi_id' => 73, 'anggota_id' => 138, 'absen_status' => 'Sakit', 'absen_note' => 'Panas'],
            ['absen_detail_id' => 146, 'absensi_id' => 74, 'anggota_id' => 143, 'absen_status' => 'Izin', 'absen_note' => 'Urusan Keluarga'],
            ['absen_detail_id' => 147, 'absensi_id' => 74, 'anggota_id' => 141, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 148, 'absensi_id' => 75, 'anggota_id' => 138, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 149, 'absensi_id' => 75, 'anggota_id' => 139, 'absen_status' => 'Dinas', 'absen_note' => 'Kalimantan'],
            ['absen_detail_id' => 150, 'absensi_id' => 75, 'anggota_id' => 140, 'absen_status' => 'Sakit', 'absen_note' => 'Diare'],
            ['absen_detail_id' => 151, 'absensi_id' => 76, 'anggota_id' => 143, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 152, 'absensi_id' => 76, 'anggota_id' => 141, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 153, 'absensi_id' => 77, 'anggota_id' => 145, 'absen_status' => 'Sakit', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 154, 'absensi_id' => 78, 'anggota_id' => 150, 'absen_status' => 'Dinas', 'absen_note' => 'Luar Kota'],
            ['absen_detail_id' => 155, 'absensi_id' => 78, 'anggota_id' => 148, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 156, 'absensi_id' => 79, 'anggota_id' => 145, 'absen_status' => 'Izin', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 157, 'absensi_id' => 79, 'anggota_id' => 146, 'absen_status' => 'Izin', 'absen_note' => 'Batuk'],
            ['absen_detail_id' => 158, 'absensi_id' => 79, 'anggota_id' => 147, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 159, 'absensi_id' => 80, 'anggota_id' => 150, 'absen_status' => 'Sakit', 'absen_note' => 'Panas'],
            ['absen_detail_id' => 160, 'absensi_id' => 80, 'anggota_id' => 148, 'absen_status' => 'Izin', 'absen_note' => 'Urusan Keluarga'],
            ['absen_detail_id' => 161, 'absensi_id' => 81, 'anggota_id' => 152, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 162, 'absensi_id' => 82, 'anggota_id' => 157, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 163, 'absensi_id' => 82, 'anggota_id' => 155, 'absen_status' => 'Dinas', 'absen_note' => 'Kalimantan'],
            ['absen_detail_id' => 164, 'absensi_id' => 83, 'anggota_id' => 152, 'absen_status' => 'Sakit', 'absen_note' => 'Diare'],
            ['absen_detail_id' => 165, 'absensi_id' => 83, 'anggota_id' => 153, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 166, 'absensi_id' => 83, 'anggota_id' => 154, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 167, 'absensi_id' => 84, 'anggota_id' => 157, 'absen_status' => 'Izin', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 168, 'absensi_id' => 84, 'anggota_id' => 155, 'absen_status' => 'Izin', 'absen_note' => 'Batuk'],
            ['absen_detail_id' => 169, 'absensi_id' => 85, 'anggota_id' => 159, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 170, 'absensi_id' => 86, 'anggota_id' => 164, 'absen_status' => 'Sakit', 'absen_note' => 'Panas'],
            ['absen_detail_id' => 171, 'absensi_id' => 86, 'anggota_id' => 162, 'absen_status' => 'Izin', 'absen_note' => 'Urusan Keluarga'],
            ['absen_detail_id' => 172, 'absensi_id' => 87, 'anggota_id' => 159, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 173, 'absensi_id' => 87, 'anggota_id' => 160, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 174, 'absensi_id' => 87, 'anggota_id' => 161, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 175, 'absensi_id' => 88, 'anggota_id' => 164, 'absen_status' => 'Sakit', 'absen_note' => 'Diare'],
            ['absen_detail_id' => 176, 'absensi_id' => 88, 'anggota_id' => 162, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 177, 'absensi_id' => 89, 'anggota_id' => 166, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 178, 'absensi_id' => 90, 'anggota_id' => 171, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 179, 'absensi_id' => 90, 'anggota_id' => 169, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 180, 'absensi_id' => 91, 'anggota_id' => 166, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 181, 'absensi_id' => 91, 'anggota_id' => 167, 'absen_status' => 'Sakit', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 182, 'absensi_id' => 91, 'anggota_id' => 168, 'absen_status' => 'Dinas', 'absen_note' => 'Luar Kota'],
            ['absen_detail_id' => 183, 'absensi_id' => 92, 'anggota_id' => 171, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 184, 'absensi_id' => 92, 'anggota_id' => 169, 'absen_status' => 'Izin', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 185, 'absensi_id' => 93, 'anggota_id' => 173, 'absen_status' => 'Izin', 'absen_note' => 'Batuk'],
            ['absen_detail_id' => 186, 'absensi_id' => 94, 'anggota_id' => 178, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 187, 'absensi_id' => 94, 'anggota_id' => 176, 'absen_status' => 'Sakit', 'absen_note' => 'Panas'],
            ['absen_detail_id' => 188, 'absensi_id' => 95, 'anggota_id' => 173, 'absen_status' => 'Izin', 'absen_note' => 'Urusan Keluarga'],
            ['absen_detail_id' => 189, 'absensi_id' => 95, 'anggota_id' => 174, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 190, 'absensi_id' => 95, 'anggota_id' => 175, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 191, 'absensi_id' => 96, 'anggota_id' => 178, 'absen_status' => 'Dinas', 'absen_note' => 'Kalimantan'],
            ['absen_detail_id' => 192, 'absensi_id' => 96, 'anggota_id' => 176, 'absen_status' => 'Sakit', 'absen_note' => 'Diare'],
            ['absen_detail_id' => 193, 'absensi_id' => 97, 'anggota_id' => 180, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 194, 'absensi_id' => 98, 'anggota_id' => 185, 'absen_status' => 'Sakit', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 195, 'absensi_id' => 98, 'anggota_id' => 183, 'absen_status' => 'Dinas', 'absen_note' => 'Luar Kota'],
            ['absen_detail_id' => 196, 'absensi_id' => 99, 'anggota_id' => 180, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 197, 'absensi_id' => 99, 'anggota_id' => 181, 'absen_status' => 'Izin', 'absen_note' => 'Demam'],
            ['absen_detail_id' => 198, 'absensi_id' => 99, 'anggota_id' => 182, 'absen_status' => 'Izin', 'absen_note' => 'Batuk'],
            ['absen_detail_id' => 199, 'absensi_id' => 100, 'anggota_id' => 185, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 200, 'absensi_id' => 100, 'anggota_id' => 183, 'absen_status' => 'Sakit', 'absen_note' => 'Panas'],
            ['absen_detail_id' => 201, 'absensi_id' => 101, 'anggota_id' => 187, 'absen_status' => 'Izin', 'absen_note' => 'Urusan Keluarga'],
            ['absen_detail_id' => 202, 'absensi_id' => 102, 'anggota_id' => 192, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 203, 'absensi_id' => 102, 'anggota_id' => 190, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 204, 'absensi_id' => 103, 'anggota_id' => 187, 'absen_status' => 'Dinas', 'absen_note' => 'Kalimantan'],
            ['absen_detail_id' => 205, 'absensi_id' => 103, 'anggota_id' => 188, 'absen_status' => 'Sakit', 'absen_note' => 'Diare'],
            ['absen_detail_id' => 206, 'absensi_id' => 103, 'anggota_id' => 189, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 207, 'absensi_id' => 104, 'anggota_id' => 192, 'absen_status' => 'Sakit', 'absen_note' => 'Sakit Kepala'],
            ['absen_detail_id' => 208, 'absensi_id' => 104, 'anggota_id' => 190, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 209, 'absensi_id' => 105, 'anggota_id' => 194, 'absen_status' => 'Izin', 'absen_note' => ''],
            ['absen_detail_id' => 210, 'absensi_id' => 106, 'anggota_id' => 199, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 211, 'absensi_id' => 106, 'anggota_id' => 197, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
            ['absen_detail_id' => 212, 'absensi_id' => 107, 'anggota_id' => 194, 'absen_status' => 'Sakit', 'absen_note' => 'Tipes'],
            ['absen_detail_id' => 213, 'absensi_id' => 107, 'anggota_id' => 195, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 214, 'absensi_id' => 107, 'anggota_id' => 196, 'absen_status' => 'Izin', 'absen_note' => 'Urus Orang Tua'],
            ['absen_detail_id' => 215, 'absensi_id' => 108, 'anggota_id' => 199, 'absen_status' => 'Sakit', 'absen_note' => ''],
            ['absen_detail_id' => 216, 'absensi_id' => 108, 'anggota_id' => 197, 'absen_status' => 'Tanpa Keterangan', 'absen_note' => ''],
        ]);
    }
}
